image: node:10.16.3

pages:
  cache:
    paths:
      - node_modules/

  script:
    - yarn install # npm install
    - yarn docs:build # npm run docs:build
  artifacts:
    paths:
      - public
  only:
    - master