image: node:10.16.3

pages:
  cache:
    paths:
      - node_modules/

  script:
    - npm install # yarn install
    - npm run docs:build # yarn docs:build 
  artifacts:
    paths:
      - public
  only:
    - master